In [1]:
#imports
import pandas as pd
import numpy as np
import os
import pickle
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import __version__ as sklearn_version
from sklearn.decomposition import PCA
from sklearn.preprocessing import scale
from sklearn.model_selection import train_test_split, cross_validate, GridSearchCV, learning_curve
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.dummy import DummyRegressor
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error
from sklearn.pipeline import make_pipeline
from sklearn.impute import SimpleImputer
from sklearn.feature_selection import SelectKBest, f_regression
import datetime

from library.sb_utils import save_file

In [2]:
#Load Data
ski_data = pd.read_csv('../clean_data/ski_data_step3_features.csv')
ski_data.head(10).T

0                    1  \
Name                                Alyeska Resort  Eaglecrest Ski Area   
Region                                      Alaska               Alaska   
state                                       Alaska               Alaska   
summit_elev                                   3939                 2600   
vertical_drop                                 2500                 1540   
base_elev                                      250                 1200   
trams                                            1                    0   
fastSixes                                        0                    0   
fastQuads                                        2                    0   
quad                                             2                    0   
triple                                           0                    0   
double                                           0                    4   
surface                                          2                    0   
total_chairs                                     7                    4   
Runs                                          76.0                 36.0   
TerrainParks                                   2.0                  1.0   
LongestRun_mi                                  1.0                  2.0   
SkiableTerrain_ac                           1610.0                640.0   
Snow Making_ac                               113.0                 60.0   
daysOpenLastYear                             150.0                 45.0   
yearsOpen                                     60.0                 44.0   
averageSnowfall                              669.0                350.0   
AdultWeekend                                  85.0                 53.0   
projectedDaysOpen                            150.0                 90.0   
NightSkiing_ac                               550.0                  NaN   
resorts_per_state                                3                    3   
resorts_per_100kcapita                    0.410091             0.410091   
resorts_per_100ksq_mile                   0.450867             0.450867   
resort_skiable_area_ac_state_ratio         0.70614             0.280702   
resort_days_open_state_ratio              0.434783             0.130435   
resort_terrain_park_state_ratio                0.5                 0.25   
resorts_night_skiing_state_ratio          0.948276                  NaN   
total_chairs_runs_ratio                   0.092105             0.111111   
total_chairs_skiable_ratio                0.004348              0.00625   
fastQuads_runs_ratio                      0.026316                  0.0   
fastQuads_skiable_ratio                   0.001242                  0.0   

                                                   2                 3  \
Name                                Hilltop Ski Area  Arizona Snowbowl   
Region                                        Alaska           Arizona   
state                                         Alaska           Arizona   
summit_elev                                     2090             11500   
vertical_drop                                    294              2300   
base_elev                                       1796              9200   
trams                                              0                 0   
fastSixes                                          0                 1   
fastQuads                                          0                 0   
quad                                               0                 2   
triple                                             1                 2   
double                                             0                 1   
surface                                            2                 2   
total_chairs                                       3                 8   
Runs                                            13.0              55.0   
TerrainParks                                     1.0               4.0   
LongestRun_mi  

In [3]:
#Big Mountain Data
big_mountain = ski_data[ski_data.Name == 'Big Mountain Resort']

In [4]:
big_mountain.T

124
Name                                Big Mountain Resort
Region                                          Montana
state                                           Montana
summit_elev                                        6817
vertical_drop                                      2353
base_elev                                          4464
trams                                                 0
fastSixes                                             0
fastQuads                                             3
quad                                                  2
triple                                                6
double                                                0
surface                                               3
total_chairs                                         14
Runs                                              105.0
TerrainParks                                        4.0
LongestRun_mi                                       3.3
SkiableTerrain_ac                                3000.0
Snow Making_ac                                    600.0
daysOpenLastYear                                  123.0
yearsOpen                                          72.0
averageSnowfall                                   333.0
AdultWeekend                                       81.0
projectedDaysOpen                                 123.0
NightSkiing_ac                                    600.0
resorts_per_state                                    12
resorts_per_100kcapita                         1.122778
resorts_per_100ksq_mile                        8.161045
resort_skiable_area_ac_state_ratio             0.140121
resort_days_open_state_ratio                   0.129338
resort_terrain_park_state_ratio                0.148148
resorts_night_skiing_state_ratio                0.84507
total_chairs_runs_ratio                        0.133333
total_chairs_skiable_ratio                     0.004667
fastQuads_runs_ratio                           0.028571
fastQuads_skiable_ratio                           0.001

In [5]:
ski_data.shape

(277, 36)

In [6]:
ski_data = ski_data[ski_data.Name != 'Big Mountain Resort']

In [7]:
ski_data.shape

(276, 36)

In [8]:
#Train/Test Split
#important to not train ML on all the data as to not over-fit
len(ski_data) * .7, len(ski_data) * .3

(193.2, 82.8)

In [9]:
X_train, X_test, y_train, y_test = train_test_split(ski_data.drop(columns='AdultWeekend'), 
                                                    ski_data.AdultWeekend, test_size=0.3, 
                                                    random_state=47)

In [10]:
X_train.shape, X_test.shape

((193, 35), (83, 35))

In [11]:
y_train.shape, y_test.shape

((193,), (83,))

In [12]:
#save the 'Name', 'state', 'Region' columns from the train/test data into names_train and names_test
#then drop the columns from X_train and x_test
names_list = ['Name', 'state', 'Region']
names_train = X_train[names_list]
names_test = X_test[names_list]
X_train.drop(columns=names_list, inplace= True)
X_test.drop(columns=names_list, inplace=True)

In [13]:
X_train.dtypes

summit_elev                             int64
vertical_drop                           int64
base_elev                               int64
trams                                   int64
fastSixes                               int64
fastQuads                               int64
quad                                    int64
triple                                  int64
double                                  int64
surface                                 int64
total_chairs                            int64
Runs                                  float64
TerrainParks                          float64
LongestRun_mi                         float64
SkiableTerrain_ac                     float64
Snow Making_ac                        float64
daysOpenLastYear                      float64
yearsOpen                             float64
averageSnowfall                       float64
projectedDaysOpen                     float64
NightSkiing_ac                        float64
resorts_per_state                 

In [14]:
X_test.dtypes

summit_elev                             int64
vertical_drop                           int64
base_elev                               int64
trams                                   int64
fastSixes                               int64
fastQuads                               int64
quad                                    int64
triple                                  int64
double                                  int64
surface                                 int64
total_chairs                            int64
Runs                                  float64
TerrainParks                          float64
LongestRun_mi                         float64
SkiableTerrain_ac                     float64
Snow Making_ac                        float64
daysOpenLastYear                      float64
yearsOpen                             float64
averageSnowfall                       float64
projectedDaysOpen                     float64
NightSkiing_ac                        float64
resorts_per_state                 

In [15]:
#Initial Not-Even-A-Model
#calc mean of y_train
train_mean = y_train.mean()
train_mean

63.811088082901556

In [16]:
dumb_reg= DummyRegressor(strategy='mean')
dumb_reg.fit(X_train, y_train)
dumb_reg.constant_

array([[63.81108808]])

In [17]:
#Calculate the R^2 as defined above
def r_squared(y, ypred):
    """R-squared score.
    
    Calculate the R-squared, or coefficient of determination, of the input.
    
    Arguments:
    y -- the observed values
    ypred -- the predicted values
    """
    ybar = np.sum(y) / len(y) #yes, we could use np.mean(y)
    sum_sq_tot = np.sum((y - ybar)**2) #total sum of squares error
    sum_sq_res = np.sum((y - ypred)**2) #residual sum of squares error
    R2 = 1.0 - sum_sq_res / sum_sq_tot
    return R2

In [18]:
y_tr_pred_ = train_mean * np.ones(len(y_train))
y_tr_pred_[:5]

array([63.81108808, 63.81108808, 63.81108808, 63.81108808, 63.81108808])

In [19]:
y_tr_pred_ = dumb_reg.predict(X_train)
y_tr_pred_[:5]

array([63.81108808, 63.81108808, 63.81108808, 63.81108808, 63.81108808])

In [20]:
r_squared(y_train,y_tr_pred_)

0.0

In [21]:
y_te_pred  = train_mean * np.ones(len(y_test))
r_squared(y_test, y_te_pred)

-0.0031235200417913944

In [22]:
#Code task 7#
#Calculate the MAE as defined above
def mae(y, ypred):
    """Mean absolute error.
    
    Calculate the mean absolute error of the arguments

    Arguments:
    y -- the observed values
    ypred -- the predicted values
    """
    abs_error = np.abs(y - ypred)
    mae = np.mean(abs_error)
    return mae

In [23]:
mae(y_train, y_tr_pred_)

17.923463717146785

In [24]:
mae(y_test, y_te_pred)

19.136142081278486